# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DcUpdate < Formula
  desc "An opinionated script for updating large docker-compose based systems"
  homepage "https://github.com/tedkulp/dc-update"
  version "2.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.4/dc-update_Darwin_x86_64.tar.gz"
      sha256 "5d4ae554abc9ff058d4e84f0408a05e7612812d2ae43f951b6ca22101b1edc73"

      def install
        bin.install "dc-update"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.4/dc-update_Darwin_arm64.tar.gz"
      sha256 "4dd3792bbbf2c2963d0280e8bf09d14e89ffb60748c52f05ee608445e71b0b0a"

      def install
        bin.install "dc-update"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.4/dc-update_Linux_x86_64.tar.gz"
      sha256 "a962dcb46cea1f2c7d63d703ef621263dd77e8a202fabd424e32d88611b690e3"
      def install
        bin.install "dc-update"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.4/dc-update_Linux_arm64.tar.gz"
      sha256 "6404fa31eada2980d1deae7c873b0d4e4e8a82d61c2f8e8b425e9b3a32cc144a"
      def install
        bin.install "dc-update"
      end
    end
  end

  test do
    system "#{bin}/dc-update --help"
  end
end
