# This file was generated by GoReleaser. DO NOT EDIT.
cask "drops" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "ebe550eb99adfb744da2b61232dea713719c61c617e4fe94b62161f6c47c576f"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "20cb9c7e215569c5155d26d41a9da5e4b5683e04564a6b8fa929492c7ac09b7f"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f16385eb8984dbc0ddfc4bc1a44288d4fa38eca17c89896eb3989913b2dc7910"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "57920ce56db87a6b7577c3c92a571c1a65e094564897fe3c9551b1aeee15ad08"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "drops"
  desc "A cross-project issue tracker for AI coding agents"
  homepage "https://github.com/tedkulp/drops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drops"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/drops"]
    end
  end

  # No zap stanza required
end
