# This file was generated by GoReleaser. DO NOT EDIT.
cask "drops" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/drops"]
    end
  end

  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "b1d339d3ed0781c830b472e8d66c384adcd6bf8a07db88e4610975c39c457862"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b919ed08a3e26dcabd7d64db3da4f940a2eb0bd6947dbb2ae453ead87ba28f8f"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "742f861d80112d75ddc92e07dd1f74588f3f3e4f3c14642a5d019358ed861cd6"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "99fdd0cdc694ff86859ed9c361085a4607d1577b92e6cead98b3d796d75067e6"
      url "https://github.com/tedkulp/drops/releases/download/v#{version}/drops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "drops"
  desc "A cross-project issue tracker for AI coding agents"
  homepage "https://github.com/tedkulp/drops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "drops"

  # No zap stanza required
end
