# This file was generated by GoReleaser. DO NOT EDIT.
cask "pholio" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "73f08687d34fdb58156109a8fdcc67571bda724a23da483931c869f9d7f9591b"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "29d4b0b6488404753fbfbab41343af5fa2c0414162410c5a87481b60cdeeb849"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2bd69e50c95a69551c18574ca8bbe868b6c544fef56a468689378c3b927450e6"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0519aae7fab319bd468fc7df796c230ba4de3a0acc3291e40309f28f8fb3e638"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pholio"
  desc "A terminal markdown editor with Daily Notes, Zettels and a vault-wide Task List"
  homepage "https://github.com/tedkulp/pholio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pholio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pholio"]
    end
  end

  # No zap stanza required
end
