# This file was generated by GoReleaser. DO NOT EDIT.
cask "pholio" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "127b5f0f20fd7bba35f73c75ec083f27e978fa90e00b6f692bc25d50dc5c4f87"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c107c448a71e192c92fd415af7b95264deec216c7781f1d57126accd90f22daa"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03cdde4fc6e552cbe418347b7d9260f643617ee9bf670115479c18e9918f9220"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d82f9467b8ce0dbd5a2dab265b1569bce793cb8edf74056ea5ada76fa393be59"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pholio"
  desc "A terminal markdown editor with Daily Notes, Zettels and a vault-wide Task List"
  homepage "https://github.com/tedkulp/pholio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pholio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pholio"]
    end
  end

  # No zap stanza required
end
