# This file was generated by GoReleaser. DO NOT EDIT.
cask "pholio" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "d27a7c65c3aa148a4e05c4fbe376762d91e655ed4be4de617f812084513e1049"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e89e9f55c09dc4f7df951d4c99d1159c87ba3283f44019fcbd82e7f5a9abd1f6"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "82a3eee3fc9c82edd20fffbad0f5a9e0957ec6fa297987a46781a4a1b400015a"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "853a8069004bcc8abf97df9a80acbd25514874f5bbac75af50e2c8e74b4972d2"
      url "https://github.com/tedkulp/pholio/releases/download/v#{version}/pholio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pholio"
  desc "A terminal markdown editor with Daily Notes, Zettels and a vault-wide Task List"
  homepage "https://github.com/tedkulp/pholio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pholio"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pholio"]
    end
  end

  # No zap stanza required
end
