# This file was generated by GoReleaser. DO NOT EDIT.
cask "tix" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "71f7543625919e86971d158cd34eda62b48fe79e59c86ca7a9c70bac9f083bfb"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedkulp/tix"
    end
    on_intel do
      sha256 "356c0551b6dbd65afbb022fcc666071d16b6b25413fe866011713e4e2a902f79"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedkulp/tix"
    end
  end
  on_linux do
    on_arm do
      sha256 "bffcae8e3708e2689fdb1d91bed8e09b4420693d37f49b62e06d0862f66a1965"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedkulp/tix"
    end
    on_intel do
      sha256 "d7865898f374a92b4dad7585736d40c4e8b730f6e54eb9531364b0da538d8e52"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedkulp/tix"
    end
  end

  name "tix"
  desc "A CLI tool for creating tickets and branches in Git repositories"
  homepage "https://github.com/tedkulp/tix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tix"]
    end
  end

  # No zap stanza required
end
