# This file was generated by GoReleaser. DO NOT EDIT.
cask "tix" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/tix"]
    end
  end

  version "0.10.4"

  on_macos do
    on_arm do
      sha256 "238c1c751b5fb5c89d3ed55aa53ddeb09d7932a63627800fc8060c67115f08b4"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d16d07ad66fc72abf82cbd88bf87958ada4b1f7a3a919a3fc6909b2634d91fc8"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "187c5b619a71dece27c49b3b1de9ee4d5793e10c178c91739d95c85914b3f587"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ecf64aac5132caac01a98523beb5a3464b0e3f1777b7ff22c9fdb4a08bfc5cf"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tix"
  desc "A CLI tool for creating tickets and branches in Git repositories"
  homepage "https://github.com/tedkulp/tix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tix"

  # No zap stanza required
end
