# This file was generated by GoReleaser. DO NOT EDIT.
cask "tix" do
  version "0.10.3"

  on_macos do
    on_arm do
      sha256 "c18dd6ed7f7a245bb7e5552e2abf444758675e18168fe60834af81b6376d9b6c"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d27f774a682342442a27a313c58c1cc734355fa00cd47fbbdd37901f3310190f"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1206e7845242aed26a606a64ea4174a9ee5c48ba5a8e9adb8d87ba7ebb991f8e"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f43d41583e0014f384da0dfbb002a48b891d1ff8a6afab2090adbae962423eb4"
      url "https://github.com/tedkulp/tix/releases/download/v#{version}/tix_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tix"
  desc "A CLI tool for creating tickets and branches in Git repositories"
  homepage "https://github.com/tedkulp/tix"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tix"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tix"]
    end
  end

  # No zap stanza required
end
