# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DcUpdate < Formula
  desc "An opinionated script for updating large docker-compose based systems"
  homepage "https://github.com/tedkulp/dc-update"
  version "2.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.5/dc-update_Darwin_x86_64.tar.gz"
      sha256 "c8f0ab0d9a838ccd96f837cba9b5e747dde1f21df0085b7f5e9bb4847b3bb9bd"

      def install
        bin.install "dc-update"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.5/dc-update_Darwin_arm64.tar.gz"
      sha256 "dd116f1522984c2a31bceabd0327aaf5694dadc860fd7451a435ce49fc35f741"

      def install
        bin.install "dc-update"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.5/dc-update_Linux_x86_64.tar.gz"
      sha256 "7a4444de0b88ce6968dcec34fe3e34d59cd0c54afd106458dd2304c29400a289"
      def install
        bin.install "dc-update"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/dc-update/releases/download/v2.0.5/dc-update_Linux_arm64.tar.gz"
      sha256 "974363c11138a45bc255ae3dc43537479d96237112b3b82fdb360b6b6ad5d55d"
      def install
        bin.install "dc-update"
      end
    end
  end

  test do
    system "#{bin}/dc-update --help"
  end
end
