# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tix < Formula
  desc "A CLI tool for creating tickets and branches in Git repositories"
  homepage "https://github.com/tedkulp/tix"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedkulp/tix/releases/download/v0.6.4/tix_0.6.4_darwin_amd64.tar.gz"
      sha256 "bef7e52f53354ab3f5089f70205985645c4c7d1e873829561a0de49dd4092759"

      def install
        bin.install "tix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedkulp/tix/releases/download/v0.6.4/tix_0.6.4_darwin_arm64.tar.gz"
      sha256 "cb3e3e0ed2067c6724349feab6f0017753480f0f1e7441062d1a6431ea78cec6"

      def install
        bin.install "tix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/tix/releases/download/v0.6.4/tix_0.6.4_linux_amd64.tar.gz"
      sha256 "075eb44ca4d0b492b0785279f41f813845d1bd02446c48fdda6aa8257e4456d7"
      def install
        bin.install "tix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/tix/releases/download/v0.6.4/tix_0.6.4_linux_arm64.tar.gz"
      sha256 "775e788bdb59a698e7f22558b84e29ca4c3d1c050c4c3d7e4a2211a864c3f3a2"
      def install
        bin.install "tix"
      end
    end
  end

  test do
    system "#{bin}/tix --version"
  end
end
