# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tix < Formula
  desc "A CLI tool for creating tickets and branches in Git repositories"
  homepage "https://github.com/tedkulp/tix"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tedkulp/tix/releases/download/v0.7.0/tix_0.7.0_darwin_amd64.tar.gz"
      sha256 "1915a23a289457cd8dafdef75a0748f6b768a6d42e735792345db61040df5702"

      define_method(:install) do
        bin.install "tix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tedkulp/tix/releases/download/v0.7.0/tix_0.7.0_darwin_arm64.tar.gz"
      sha256 "39c5ac8f05269c9c5dfac0f77badd5bb07a88460bf7dcc4a35d288cfe7bb035e"

      define_method(:install) do
        bin.install "tix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/tix/releases/download/v0.7.0/tix_0.7.0_linux_amd64.tar.gz"
      sha256 "ca473f3c3492e0de9afb93ff1c870e3c0076e146215f4b4c08c9d0700aafb86a"
      define_method(:install) do
        bin.install "tix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tedkulp/tix/releases/download/v0.7.0/tix_0.7.0_linux_arm64.tar.gz"
      sha256 "32f8baee2d9d02f49b1d8fee5f5e48125524725c6be53b9da6b57e329a869f8b"
      define_method(:install) do
        bin.install "tix"
      end
    end
  end

  test do
    system "#{bin}/tix --version"
  end
end
